name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - name: Obtain GLFW dependency
      run: >
        sudo apt-get install libglfw3-dev vulkan-tools libvulkan-dev

    - name: Fetch GLFWAda
      uses: actions/checkout@master
      with:
        repository: zrmyers/GLFWAda
        ref: master
        path: GLFWAda

    - name: Build GLFWAda
      working-directory: GLFWAda
      run: >
          export GLFWADA_GPR=GLFWAda/glfwada.gpr &&
          make compile

    - name: Build
      run: >
        export platform="linux" &&
        make

    - name: Test Vulkan Math Package
      run: >
        ./bin/vulkan_test-math
