name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - run: cd ../

    - name: Fetch GLFWAda
      uses: actions/checkout@master
      with:
        repository: zrmyers/GLFWAda
        ref: master
        path: ./

    - run: find -name GLFWAda
    - run: cd GLFWAda
    - run: make install
    - run: cd ../VulkanAda

    - name: Build
      run: make
